CL_Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.welcome_view, name='home'),
    url(r'^songs/', include('songs.urls', namespace='songs')),
]

urlpatterns += staticfiles_urlpatterns()

songs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #URL for ListView
    url(r'^$', views.SongListView.as_view(), name='list'),
    #URLs for CRUD Views
    url(r'^(?P<pk>\d+)/$', views.SongDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SongCreateView.as_view(), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', views.SongUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SongDeleteView.as_view(), name='delete'),
]

songs/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse

#Creation of only model in project.  Could be expanded later for more detail or
#could build new models and link with foreign keys.
class Song(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255, default="N/A")
    composition_date = models.PositiveIntegerField(default=1900)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('songs:detail', kwargs={'pk': self.pk})

CL_Project/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render


def welcome_view(request):
    return render(request, 'home.html')

songs/views.py
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView, DetailView,
    CreateView, UpdateView, DeleteView
)


from . import models


def song_list(request):
    songs = models.Song.objects.all()
    return render(request, 'song_list.html', {'songs': songs})

class SongListView(ListView):
    context_object_name = 'songs'
    model = models.Song

# Create Views for full CRUD capabilities

class SongDetailView(DetailView):
    model = models.Song

class SongCreateView(CreateView):
    fields = ('title', 'artist', 'composition_date')
    model = models.Song

class SongUpdateView(UpdateView):
    fields = ('title', 'artist', 'composition_date')
    model = models.Song

class SongDeleteView(DeleteView):
    model = models.Song
    success_url = reverse_lazy("songs:list")

songs/templates/song_details.html
<table>
    <tr>
        <th>Title</th>
        <th>Artist</th> 
        <th>Date</th>
    </tr>
    
    {% for song in songs %}
        <tr>
            <td>{{ song.title }}</td>
            <td>{{ song.artist }}</td>
            <td>{{ song.composition_date }}</td>
        </tr>
    {% endfor %}
    
</table> 

songs/templates/songs/layout.html
{% extends "layout.html" %}

{% block title %} Songs | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'songs:list' %}">Songs</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

songs/templates/songs/song_confirm_delete.html
<!-- Asks user if they really want to delete the song from the database. -->
{% extends "layout.html" %}

{% block content %}
<div class="margin-center">
	<h1>Delete {{ song.title }} by {{ song.artist }}?</h1>

	<form method='POST'>
		{% csrf_token %}
		<input type="submit" class="button delete" value="Delete"> <a href="{% url 'songs:list' %}">Cancel</a>
	</form>
</div>
{% endblock %}

songs/templates/songs/song_detail.html
{% extends "layout.html" %}

{% block content %}
<div class="margin-center">

  <p>Title: {{ song.title}}</p>
  <p>Artist: {{ song.artist}}</p>
  <p>Date: {{ song.composition_date}}</p>

  <a id="detail-button" href="{% url 'songs:list' %}">Back to the list!</a>
</div>
{% endblock %}

songs/templates/songs/song_form.html
{% extends "layout.html" %}

{% block content %}
<div class="form">
    {{ block.super }}
    <h1>{{ form.instance.title|default:"Add a New Song" }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button save" value="Save"> <a href="{% url 'songs:list' %}">Cancel</a>
    </form>
</div>

{% endblock %}

songs/templates/songs/song_list.html
<!-- Table for addition of new songs to database. -->
{% extends "layout.html" %}
{% load static from staticfiles %}


{% block content %}
<h3 id="new-song"><a href="{% url 'songs:create' %}">Add a New Song</a></h3>


<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Date</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

    {% for song in songs %}
        <tr>
            <td>{{ song.title }}</td>
            <td>{{ song.artist }}</td>
            <td>{{ song.composition_date }}</td>
            <td>
              <a href="{% url 'songs:update' pk=song.pk %}">
                <img style="width:25px; height: 25px; padding-left: 3px;" src="{% static 'img/edit-icon.png' %}" />
              </a>
            </td>
            <td>
              <a href="{% url 'songs:delete' pk=song.pk %}">
                <img style="width:25px; height: 25px; padding-left: 3px;" src="{% static 'img/delete-icon.png' %}" />
              </a>
            </td>
        </tr>
    {% endfor %}

</table>

{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %} Song a Day {% endblock %}

{% block content %}
    <div class="home-body">
        <h1>Rogue Middle Child Presents:</h1>
        <h2>Song a Day</h2>
        <p>An adventure in Python and Django</p>
        <p id="enter"><a href="{% url 'songs:list' %}">Enter Here</a></p>
    </div>
{% endblock %}

templates/layout.html
<!-- Basic layout to be extended by home -->
<!doctype html>
{% load static from staticfiles %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport">
        <title>{% block title %}{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block css %}{% endblock %}
    </head>

    <body>
    <div class="page-wrap">
          <header class="main-header">
            <h2 class="main-logo">Song a Day:</h2>
            <h2 class="main-nav"><a href="{% url 'songs:list' %}">Song List</a></h2>
          </header>
        <div class="body">


    {% block content %}{% endblock %}
        </div>
    </div>

    <footer class="site-footer">

      <div>
          <p>&copy; 2017 Rogue Middle Child</p>


      </div>

    </footer>

  </body>
</html>